import Foundation

extension Country {
    static let samples: [Country] = {
        func flag(_ code: String) -> URL {
            URL(string: "https://flagcdn.com/w320/\(code).png") ?? URL(fileURLWithPath: "")
        }
        return [
            Country(id: "Nigeria",       name: "Nigeria",       officialName: "Federal Republic of Nigeria",       flagURL: flag("ng"), flagSVGURL: nil, region: "Africa",   subregion: "Western Africa",            currencies: [Currency(name: "Nigerian naira",         symbol: "₦")],  population: 218_541_000, capital: ["Abuja"],            mapsURL: nil, tld: [".ng"],  languages: ["English"]),
            Country(id: "Egypt",         name: "Egypt",         officialName: "Arab Republic of Egypt",            flagURL: flag("eg"), flagSVGURL: nil, region: "Africa",   subregion: "Northern Africa",           currencies: [Currency(name: "Egyptian pound",         symbol: "£")],  population: 104_258_000, capital: ["Cairo"],            mapsURL: nil, tld: [".eg"],  languages: ["Arabic"]),
            Country(id: "Kenya",         name: "Kenya",         officialName: "Republic of Kenya",                 flagURL: flag("ke"), flagSVGURL: nil, region: "Africa",   subregion: "Eastern Africa",            currencies: [Currency(name: "Kenyan shilling",        symbol: "KSh")],population:  54_027_000, capital: ["Nairobi"],          mapsURL: nil, tld: [".ke"],  languages: ["English", "Swahili"]),
            Country(id: "South Africa",  name: "South Africa",  officialName: "Republic of South Africa",          flagURL: flag("za"), flagSVGURL: nil, region: "Africa",   subregion: "Southern Africa",           currencies: [Currency(name: "South African rand",     symbol: "R")],  population:  60_041_000, capital: ["Pretoria"],         mapsURL: nil, tld: [".za"],  languages: ["Afrikaans", "English", "Zulu", "Xhosa"]),
            Country(id: "Japan",         name: "Japan",         officialName: "Japan",                             flagURL: flag("jp"), flagSVGURL: nil, region: "Asia",     subregion: "Eastern Asia",              currencies: [Currency(name: "Japanese yen",           symbol: "¥")],  population: 125_681_000, capital: ["Tokyo"],            mapsURL: nil, tld: [".jp"],  languages: ["Japanese"]),
            Country(id: "China",         name: "China",         officialName: "People's Republic of China",        flagURL: flag("cn"), flagSVGURL: nil, region: "Asia",     subregion: "Eastern Asia",              currencies: [Currency(name: "Chinese yuan",           symbol: "¥")],  population: 1_402_112_000,capital: ["Beijing"],          mapsURL: nil, tld: [".cn"],  languages: ["Chinese"]),
            Country(id: "India",         name: "India",         officialName: "Republic of India",                 flagURL: flag("in"), flagSVGURL: nil, region: "Asia",     subregion: "Southern Asia",             currencies: [Currency(name: "Indian rupee",           symbol: "₹")],  population: 1_380_004_000,capital: ["New Delhi"],        mapsURL: nil, tld: [".in"],  languages: ["English", "Hindi"]),
            Country(id: "South Korea",   name: "South Korea",   officialName: "Republic of Korea",                 flagURL: flag("kr"), flagSVGURL: nil, region: "Asia",     subregion: "Eastern Asia",              currencies: [Currency(name: "South Korean won",       symbol: "₩")],  population:  51_780_000, capital: ["Seoul"],            mapsURL: nil, tld: [".kr"],  languages: ["Korean"]),
            Country(id: "France",        name: "France",        officialName: "French Republic",                   flagURL: flag("fr"), flagSVGURL: nil, region: "Europe",   subregion: "Western Europe",            currencies: [Currency(name: "Euro",                   symbol: "€")],  population:  67_391_000, capital: ["Paris"],            mapsURL: nil, tld: [".fr"],  languages: ["French"]),
            Country(id: "Germany",       name: "Germany",       officialName: "Federal Republic of Germany",       flagURL: flag("de"), flagSVGURL: nil, region: "Europe",   subregion: "Western Europe",            currencies: [Currency(name: "Euro",                   symbol: "€")],  population:  83_240_000, capital: ["Berlin"],           mapsURL: nil, tld: [".de"],  languages: ["German"]),
            Country(id: "Italy",         name: "Italy",         officialName: "Italian Republic",                  flagURL: flag("it"), flagSVGURL: nil, region: "Europe",   subregion: "Southern Europe",           currencies: [Currency(name: "Euro",                   symbol: "€")],  population:  60_362_000, capital: ["Rome"],             mapsURL: nil, tld: [".it"],  languages: ["Italian"]),
            Country(id: "Spain",         name: "Spain",         officialName: "Kingdom of Spain",                  flagURL: flag("es"), flagSVGURL: nil, region: "Europe",   subregion: "Southern Europe",           currencies: [Currency(name: "Euro",                   symbol: "€")],  population:  47_351_000, capital: ["Madrid"],           mapsURL: nil, tld: [".es"],  languages: ["Spanish"]),
            Country(id: "United States", name: "United States", officialName: "United States of America",          flagURL: flag("us"), flagSVGURL: nil, region: "Americas", subregion: "North America",             currencies: [Currency(name: "United States dollar",   symbol: "$")],  population: 329_484_000, capital: ["Washington, D.C."], mapsURL: nil, tld: [".us"],  languages: ["English"]),
            Country(id: "Canada",        name: "Canada",        officialName: "Canada",                            flagURL: flag("ca"), flagSVGURL: nil, region: "Americas", subregion: "North America",             currencies: [Currency(name: "Canadian dollar",        symbol: "$")],  population:  38_005_000, capital: ["Ottawa"],           mapsURL: nil, tld: [".ca"],  languages: ["English", "French"]),
            Country(id: "Mexico",        name: "Mexico",        officialName: "United Mexican States",             flagURL: flag("mx"), flagSVGURL: nil, region: "Americas", subregion: "North America",             currencies: [Currency(name: "Mexican peso",           symbol: "$")],  population: 128_932_000, capital: ["Mexico City"],      mapsURL: nil, tld: [".mx"],  languages: ["Spanish"]),
            Country(id: "Brazil",        name: "Brazil",        officialName: "Federative Republic of Brazil",     flagURL: flag("br"), flagSVGURL: nil, region: "Americas", subregion: "South America",             currencies: [Currency(name: "Brazilian real",         symbol: "R$")], population: 214_326_000, capital: ["Brasília"],         mapsURL: nil, tld: [".br"],  languages: ["Portuguese"]),
            Country(id: "Argentina",     name: "Argentina",     officialName: "Argentine Republic",                flagURL: flag("ar"), flagSVGURL: nil, region: "Americas", subregion: "South America",             currencies: [Currency(name: "Argentine peso",         symbol: "$")],  population:  45_376_000, capital: ["Buenos Aires"],     mapsURL: nil, tld: [".ar"],  languages: ["Spanish"]),
            Country(id: "Colombia",      name: "Colombia",      officialName: "Republic of Colombia",              flagURL: flag("co"), flagSVGURL: nil, region: "Americas", subregion: "South America",             currencies: [Currency(name: "Colombian peso",         symbol: "$")],  population:  50_888_000, capital: ["Bogotá"],           mapsURL: nil, tld: [".co"],  languages: ["Spanish"]),
            Country(id: "Cuba",          name: "Cuba",          officialName: "Republic of Cuba",                  flagURL: flag("cu"), flagSVGURL: nil, region: "Americas", subregion: "Caribbean",                 currencies: [Currency(name: "Cuban convertible peso", symbol: "$"), Currency(name: "Cuban peso", symbol: "$")], population: 11_326_000, capital: ["Havana"], mapsURL: nil, tld: [".cu"], languages: ["Spanish"]),
            Country(id: "Australia",     name: "Australia",     officialName: "Commonwealth of Australia",         flagURL: flag("au"), flagSVGURL: nil, region: "Oceania",  subregion: "Australia and New Zealand", currencies: [Currency(name: "Australian dollar",      symbol: "$")],  population:  25_499_000, capital: ["Canberra"],         mapsURL: nil, tld: [".au"],  languages: ["English"]),
            Country(id: "New Zealand",   name: "New Zealand",   officialName: "New Zealand",                       flagURL: flag("nz"), flagSVGURL: nil, region: "Oceania",  subregion: "Australia and New Zealand", currencies: [Currency(name: "New Zealand dollar",     symbol: "$")],  population:   5_084_000, capital: ["Wellington"],       mapsURL: nil, tld: [".nz"],  languages: ["English", "Māori"]),
        ]
    }()
}
